export type EventType = 'meetup' | 'talks';

export interface Venue {
  name: string;
  url?: string;
}

export const venues: Record<string, Venue> = {
  'most':        { name: 'MOST IT Hub, БЦ Fortis', url: 'https://go.2gis.com/aPpbN' },
  'platforma':   { name: 'PlatformA', url: 'https://2gis.kz/almaty/geo/70000001080520349' },
  'qaynar':      { name: 'Qaynar Bulaq', url: 'https://go.2gis.com/tk6zgi' },
  'travelers':   { name: "Traveler's Coffee", url: 'https://go.2gis.com/2eqpo' },
  'myroom':      { name: 'MYROOM антикафе', url: 'https://go.2gis.com/ner3n' },
  'steppe':      { name: 'Steppe Coffee', url: 'https://2gis.kz/almaty/geo/70000001094769137' },
  'foyer':       { name: 'Foyer Coffee', url: 'https://go.2gis.com/s0lp8p' },
  'bereke':      { name: 'Bereke Bank', url: 'https://go.2gis.com/gC3uB' },
  'indrive':     { name: 'inDrive офис', url: 'https://go.2gis.com/paUfY' },
  'voronka':     { name: 'Воронка', url: 'https://2gis.kz/almaty/geo/70000001099447089' },
  'vanilla':     { name: 'Vanilla Coffee Bar', url: 'https://2gis.kz/almaty/geo/70000001103539281' },
  'shuka':       { name: 'ЩУКА bistro', url: 'https://2gis.kz/almaty/geo/70000001094617082' },
  'forum':       { name: 'ТРЦ Forum', url: 'https://go.2gis.com/v8gtxr' },
  'ogonek':      { name: 'Огонёк', url: 'https://yandex.ru/maps/-/CDReyP0Q' },
  'warpoint':    { name: 'Warpoint VR', url: 'https://go.2gis.com/iw858' },
  'community':   { name: 'Комьюнити-центр Алмалинского района', url: 'https://go.2gis.com/i9e0i' },
};

export interface Speaker {
  name: string;
  role?: string;
  topic: string;
}

export interface CommunityEvent {
  id: string;
  type: EventType;
  number: number;
  talksIndex?: number;
  date: string; // YYYY-MM-DD
  title: string;
  venueId?: string;
  topics?: string[];
  speakers?: Speaker[];
  cancelled?: boolean;
  youtubePlaylist?: string;
  image?: string; // path relative to /events/
  eventPage?: string; // internal route
}

export const events: CommunityEvent[] = [
  // === 2026 ===
  {
    id: 'talks-2',
    type: 'talks',
    number: 2,
    talksIndex: 2,
    date: '2026-04-03',
    title: 'nullptr.talks[2]',
    venueId: 'most',
    image: '/events/talks-2.jpg',
    eventPage: '/events/nullpointer-talks-2',
    speakers: [
      { name: 'Дмитрий Михальченков', role: 'Senior Android Engineer, inDrive', topic: 'Код-ревью: как перестать мучить команду' },
      { name: 'Алексей Орехов', role: 'Android Engineer', topic: 'Почему в 2026 нужно уходить из энтерпрайза и нырять в ИИ' },
      { name: 'Даурен Кассен', role: 'Android/KMP, QIC digital hub', topic: 'Compose Multiplatform — пет-проект который приносит денюжки' },
      { name: 'Иван Луценко', role: 'Android Tech Lead, Bereke Bank', topic: 'Эволюция анализа крешей: от Crashlytics до мультиагентского пайплайна' },
    ],
  },
  {
    id: 'meetup-47',
    type: 'meetup',
    number: 47,
    date: '2026-03-21',
    title: 'Meetup #47',
    venueId: 'shuka',
    topics: ['Оркестратор агентов', 'GDG x nullptr.party', 'Сабагенты и adversarial review', 'Найм и AI', 'DLSS 5', 'Open-source и Anthropic'],
  },
  {
    id: 'meetup-46',
    type: 'meetup',
    number: 46,
    date: '2026-03-07',
    title: 'Meetup #46',
    venueId: 'steppe',
    image: '/events/meetup-46.jpg',
    topics: ['Баны AI-провайдеров', 'Мобильные SSH-клиенты', 'Рынок труда в IT', 'Американские консалтинги'],
  },
  {
    id: 'meetup-45',
    type: 'meetup',
    number: 45,
    date: '2026-02-21',
    title: 'Meetup #45',
    venueId: 'voronka',
    topics: ['Голосовое управление', 'TUI-агенты', 'Claude Code'],
  },
  {
    id: 'meetup-44',
    type: 'meetup',
    number: 44,
    date: '2026-02-07',
    title: 'Meetup #44',
    venueId: 'vanilla',
    image: '/events/meetup-44.jpg',
    topics: ['Безопасность агентов', 'Рои агентов', 'Влияние ИИ на навыки', 'Бюджеты на AI-подписки'],
  },
  {
    id: 'meetup-43',
    type: 'meetup',
    number: 43,
    date: '2026-01-24',
    title: 'Meetup #43',
    venueId: 'voronka',
    topics: ['Anthropic подписки', 'Opus замедление', 'Cowork от Claude'],
  },
  {
    id: 'meetup-42',
    type: 'meetup',
    number: 42,
    date: '2026-01-10',
    title: 'Meetup #42',
    venueId: 'voronka',
    topics: ['macOS-инструменты', 'Raycast', 'Flatbar'],
  },

  // === 2025 ===
  {
    id: 'meetup-40',
    type: 'meetup',
    number: 40,
    date: '2025-11-15',
    title: 'Meetup #40',
    venueId: 'platforma',
    image: '/events/meetup-40-group.jpg',
  },
  {
    id: 'meetup-41',
    type: 'meetup',
    number: 41,
    date: '2025-12-20',
    title: 'Meetup #41',
    venueId: 'platforma',
    image: '/events/meetup-41.jpg',
    topics: ['Claude Code и MCP', 'nullptr.talks[1] разбор', 'Advent of Code', 'Remote Compose', 'JetBrains vs VS Code'],
    cancelled: true,
  },
  {
    id: 'talks-1',
    type: 'talks',
    number: 1,
    talksIndex: 1,
    date: '2025-12-12',
    title: 'nullptr.talks[1]',
    venueId: 'most',
    image: '/events/talks-1.jpg',
    eventPage: '/events/nullpointer-talks-1',
    youtubePlaylist: 'https://youtube.com/playlist?list=PL1rdjlpSaYF2yDvXse4ZF8EeZ0TmpkWjZ',
    speakers: [
      { name: 'Алексей Орехов', role: 'Android Engineer, izi', topic: 'Лебедь, рак и щука — приложение в приложении' },
      { name: 'Амин Бенариеб', role: 'iOS Engineer, Welltory', topic: 'Как мы превратили iPhone в лабораторный микроскоп' },
      { name: 'Алихан Байшоланов', role: 'Android Engineer, BCC HUB', topic: 'Запуск Dart кода через нативку' },
    ],
  },
  {
    id: 'meetup-39',
    type: 'meetup',
    number: 39,
    date: '2025-11-01',
    title: 'Meetup #39',
    venueId: 'platforma',
    image: '/events/meetup-39.jpg',
    topics: ['AI-инструменты', 'Cursor Composer', 'CLI LLM', 'Рынок труда', 'LinkedIn SSI'],
  },
  {
    id: 'meetup-38',
    type: 'meetup',
    number: 38,
    date: '2025-10-18',
    title: 'Meetup #38',
    venueId: 'platforma',
    image: '/events/meetup-38-group.jpg',
    topics: ['Неформальное общение'],
  },
  {
    id: 'meetup-37',
    type: 'meetup',
    number: 37,
    date: '2025-09-27',
    title: 'Meetup #37',
    venueId: 'platforma',
    image: '/events/meetup-37-group.jpg',
    topics: ['Разбор nullptr.talks[0]', 'MCP', 'Эргономика', 'AR/VR', 'Кибербезопасность'],
  },
  {
    id: 'talks-0',
    type: 'talks',
    number: 0,
    talksIndex: 0,
    date: '2025-09-12',
    title: 'nullptr.talks[0]',
    venueId: 'most',
    image: '/events/talks-0.jpg',
    eventPage: '/events/nullpointer-talks-0',
    youtubePlaylist: 'https://www.youtube.com/playlist?list=PL1rdjlpSaYF1Hz2docBwkHZ1IY_AkRqOn',
    speakers: [
      { name: 'Дмитрий Бузулуцкий', role: 'iOS Tech Lead, Bereke Bank', topic: 'Быть или не быть мобильным разработчиком в 2026?' },
      { name: 'Илья Гуля', role: 'Developer Productivity Engineer, inDrive', topic: 'Вайбкодинг — блажь или благо?' },
      { name: 'Дмитрий Михальченков', role: 'Senior Android Engineer, inDrive', topic: 'Фича-тогглы: друг или враг вашего дедлайна?' },
      { name: 'Данияр Амангельды', role: 'Senior Android Developer', topic: 'Android hours — тегін воркшоп' },
    ],
  },
  {
    id: 'meetup-36',
    type: 'meetup',
    number: 36,
    date: '2025-08-30',
    title: 'Meetup #36',
    venueId: 'platforma',
    image: '/events/meetup-36-group.jpg',
    topics: ['Неформальное общение'],
  },
  {
    id: 'meetup-35',
    type: 'meetup',
    number: 35,
    date: '2025-08-16',
    title: 'Meetup #35',
    venueId: 'platforma',
    image: '/events/meetup-35-group.jpg',
    topics: ['GPT-5', 'Скандал с приложением Tea', 'Этика данных'],
  },
  {
    id: 'meetup-34',
    type: 'meetup',
    number: 34,
    date: '2025-07-26',
    title: 'Meetup #34',
    venueId: 'platforma',
    image: '/events/meetup-34.jpg',
    topics: ['Агентные IDE', 'Cursor', 'Claude Code', 'Kiro', 'Copilot Agent'],
  },
  {
    id: 'meetup-33',
    type: 'meetup',
    number: 33,
    date: '2025-07-12',
    title: 'Meetup #33',
    venueId: 'platforma',
    image: '/events/meetup-33-group.jpg',
    topics: ['AI-агенты', 'AI-инструменты для кодинга', 'Практический опыт'],
  },
  {
    id: 'meetup-32',
    type: 'meetup',
    number: 32,
    date: '2025-06-27',
    title: 'Meetup #32',
    venueId: 'bereke',
    image: '/events/meetup-32.jpg',
    topics: ['Claude & MCP в работе техлида'],
  },
  {
    id: 'meetup-31',
    type: 'meetup',
    number: 31,
    date: '2025-06-13',
    title: 'Meetup #31',
    venueId: 'bereke',
    image: '/events/meetup-31-group.jpg',
    topics: ['Актуальные новости'],
  },
  {
    id: 'meetup-30',
    type: 'meetup',
    number: 30,
    date: '2025-05-23',
    title: 'Meetup #30',
    venueId: 'platforma',
    image: '/events/meetup-30.jpg',
    topics: ['Google I/O', 'MCP', 'Работа и вакансии'],
  },
  {
    id: 'meetup-29',
    type: 'meetup',
    number: 29,
    date: '2025-05-03',
    title: 'Meetup #29',
    venueId: 'bereke',
    image: '/events/meetup-29-group.jpg',
    topics: ['AI в разработке'],
  },
  {
    id: 'meetup-28',
    type: 'meetup',
    number: 28,
    date: '2025-03-15',
    title: 'Meetup #28',
    venueId: 'bereke',
    image: '/events/meetup-28.jpg',
  },
  {
    id: 'meetup-27',
    type: 'meetup',
    number: 27,
    date: '2025-02-15',
    title: 'Meetup #27',
    venueId: 'indrive',
    image: '/events/meetup-27.jpg',
  },
  {
    id: 'meetup-26',
    type: 'meetup',
    number: 26,
    date: '2025-02-01',
    title: 'Meetup #26',
    venueId: 'indrive',
    image: '/events/meetup-26.jpg',
    topics: ['Роботы-собаки', 'Мобильная разработка', 'AI-инструменты'],
  },
  {
    id: 'meetup-25',
    type: 'meetup',
    number: 25,
    date: '2025-01-11',
    title: 'Meetup #25',
    venueId: 'bereke',
    image: '/events/meetup-25.jpg',
    topics: ['Роботы-полицейские', 'AI-генерируемые профили', 'Технологические новости'],
  },

  // === 2024 ===
  {
    id: 'meetup-24',
    type: 'meetup',
    number: 24,
    date: '2024-12-21',
    title: 'Meetup #24',
    venueId: 'bereke',
    image: '/events/meetup-24.jpg',
    topics: ['Терминал и bash', 'Git в JetBrains', 'Тайловые оконные менеджеры', 'Почта на своём домене'],
  },
  {
    id: 'meetup-23',
    type: 'meetup',
    number: 23,
    date: '2024-12-07',
    title: 'Meetup #23',
    venueId: 'foyer',
    image: '/events/meetup-23.jpg',
    topics: ['AI meeting notes', 'Geminio', 'Aider', 'Cursor Agents', 'CrewAI', 'Langgraph', 'Phaser.js', 'Godot'],
  },
  {
    id: 'meetup-22',
    type: 'meetup',
    number: 22,
    date: '2024-11-23',
    title: 'Meetup #22',
    venueId: 'foyer',
    image: '/events/meetup-22.jpg',
    topics: ['Декомпиляция с AI', 'AI для кодинга', 'Тесты в Android', 'LLM-агенты', 'Edge-to-edge API 35'],
  },
  {
    id: 'meetup-21',
    type: 'meetup',
    number: 21,
    date: '2024-11-02',
    title: 'Meetup #21',
    venueId: 'foyer',
    image: '/events/meetup-21.jpg',
    topics: ['React Native New Architecture', 'Аутсорс vs аутстаф', 'Виртуальный DOM', 'Single vs Multi Activity', 'Error as value'],
  },
  {
    id: 'meetup-20',
    type: 'meetup',
    number: 20,
    date: '2024-10-12',
    title: 'Meetup #20',
    venueId: 'foyer',
    image: '/events/meetup-20.jpg',
    topics: ['Claude 3.5 Sonnet', 'Сплит-клавиатуры', 'Альтернативные раскладки', 'Linux'],
  },
  {
    id: 'meetup-19',
    type: 'meetup',
    number: 19,
    date: '2024-09-28',
    title: 'Meetup #19',
    venueId: 'foyer',
    image: '/events/meetup-19.jpg',
    topics: ['Аккаунт разработчика', 'GitHub Actions', 'Казахстанские компании', 'Asahi Linux'],
  },
  {
    id: 'meetup-18',
    type: 'meetup',
    number: 18,
    date: '2024-09-07',
    title: 'Meetup #18',
    venueId: 'foyer',
    image: '/events/meetup-18.jpg',
    topics: ['Смена профессии', 'Путь в менеджмент', 'Попытка переезда в США'],
  },
  {
    id: 'meetup-17',
    type: 'meetup',
    number: 17,
    date: '2024-07-20',
    title: 'Meetup #17',
    venueId: 'foyer',
    image: '/events/meetup-17.jpg',
    topics: ['Алгоритмы на собеседованиях', 'UK Talent Visa', 'Формат собеседований', 'Индихакинг'],
  },
  {
    id: 'meetup-16',
    type: 'meetup',
    number: 16,
    date: '2024-07-06',
    title: 'Meetup #16',
    venueId: 'foyer',
    image: '/events/meetup-16.jpg',
    topics: ['React Native vs Flutter', 'Decompose', 'Java Memory Model', 'Redwood/Zipline', 'Tech Lead vs Team Lead'],
  },
  {
    id: 'meetup-15',
    type: 'meetup',
    number: 15,
    date: '2024-06-22',
    title: 'Meetup #15',
    venueId: 'community',
    image: '/events/meetup-15.jpg',
    topics: ['Firebase Performance', 'Systrace', 'Heap dump', 'Chucker', 'Facebook Flipper'],
  },
  {
    id: 'meetup-14',
    type: 'meetup',
    number: 14,
    date: '2024-06-01',
    title: 'Meetup #14',
    venueId: 'community',
    image: '/events/meetup-14.jpg',
    topics: ['Формализация процессов', 'Системные аналитики', 'Feature ownership', 'KMP'],
  },
  {
    id: 'meetup-13',
    type: 'meetup',
    number: 13,
    date: '2024-05-18',
    title: 'Meetup #13',
    venueId: 'forum',
    topics: ['KMP vs React Native vs Flutter', 'ViewModelProvider', 'SavedStateHandle', 'Kotlin properties'],
  },
  {
    id: 'meetup-12',
    type: 'meetup',
    number: 12,
    date: '2024-04-27',
    title: 'Meetup #12',
    venueId: 'qaynar',
    image: '/events/meetup-12.jpg',
    topics: ['Источники экспертизы', 'Технический долг', 'Матрицы компетенций'],
  },
  {
    id: 'meetup-11',
    type: 'meetup',
    number: 11,
    date: '2024-04-13',
    title: 'Meetup #11',
    venueId: 'qaynar',
    topics: ['Compose Multiplatform', 'KMP миграция', 'SQLDelight', 'Arrow-kt'],
  },
  {
    id: 'meetup-10',
    type: 'meetup',
    number: 10,
    date: '2024-03-30',
    title: 'Meetup #10',
    venueId: 'qaynar',
    image: '/events/meetup-10.jpg',
    topics: ['Выгорание', 'v0.dev', 'AI-генерация UI', 'Claude 3'],
  },
  {
    id: 'meetup-09',
    type: 'meetup',
    number: 9,
    date: '2024-03-27',
    title: 'Meetup #9',
    venueId: 'ogonek',
    image: '/events/meetup-09.jpg',
    topics: ['Встреча с Алексеем Гладковым'],
  },
  {
    id: 'meetup-08',
    type: 'meetup',
    number: 8,
    date: '2024-03-16',
    title: 'Meetup #8',
    venueId: 'qaynar',
    image: '/events/meetup-08.jpg',
    topics: ['Anvil + Dagger', 'AssistedFactory', 'Gradle modules'],
  },
  {
    id: 'meetup-07',
    type: 'meetup',
    number: 7,
    date: '2024-03-02',
    title: 'Meetup #7',
    venueId: 'qaynar',
    image: '/events/meetup-07.jpg',
    topics: ['Storybook.js', 'Showkase', 'GitHub Actions', 'CI оптимизация'],
  },
  {
    id: 'meetup-06',
    type: 'meetup',
    number: 6,
    date: '2024-02-17',
    title: 'Meetup #6',
    venueId: 'qaynar',
    image: '/events/meetup-06.jpg',
    topics: ['Elm Architecture', 'MVIKotlin', 'Geminio', 'OpenAI Sora', 'Ollama'],
  },
  {
    id: 'meetup-05',
    type: 'meetup',
    number: 5,
    date: '2024-02-10',
    title: 'Meetup #5',
    venueId: 'warpoint',
    image: '/events/meetup-05.jpg',
    topics: ['VR-стрелялка', 'Неформальное общение'],
  },
  {
    id: 'meetup-04',
    type: 'meetup',
    number: 4,
    date: '2024-02-03',
    title: 'Meetup #4',
    venueId: 'qaynar',
    image: '/events/meetup-04.jpg',
    topics: ['Автотестирование', 'Appium', 'Многомодульность'],
  },
  {
    id: 'meetup-03',
    type: 'meetup',
    number: 3,
    date: '2024-01-27',
    title: 'Meetup #3',
    venueId: 'myroom',
    image: '/events/meetup-03.jpg',
    topics: ['Настолки', 'Неформальное общение'],
  },
  {
    id: 'meetup-02',
    type: 'meetup',
    number: 2,
    date: '2024-01-20',
    title: 'Meetup #2',
    venueId: 'qaynar',
    image: '/events/meetup-02.jpg',
    topics: ['Рефакторинг в IDEA', 'Arc Browser', 'GitHub Copilot', 'Тесты с AI'],
  },
  {
    id: 'meetup-01',
    type: 'meetup',
    number: 1,
    date: '2024-01-13',
    title: 'Meetup #1',
    venueId: 'travelers',
    image: '/events/meetup-01.jpg',
    topics: ['Знакомство', 'Релокация', 'Собеседования', 'Backend Driven UI'],
  },
];

export const earlyMeetupsCount = 0;

export function getEventsByYear(evts: CommunityEvent[]): Record<string, CommunityEvent[]> {
  const grouped: Record<string, CommunityEvent[]> = {};
  for (const evt of evts) {
    const year = evt.date.slice(0, 4);
    if (!grouped[year]) grouped[year] = [];
    grouped[year].push(evt);
  }
  return grouped;
}
