# .github/workflows/deploy.yml
name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.site.domain }}
    strategy:
      matrix:
        site:
          - domain: nullptr.party
            project: nullptr-party
          - domain: almaty.nullptr.party
            project: nullptr-party-almaty
      # In case one deployment fails, continue with others
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          SITE_DOMAIN: ${{ matrix.site.domain }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy out --project-name=${{ matrix.site.project }} --branch main
